import { formatForClipboard } from "../format/formatForClipboard.js";
import { renderMarkdown } from "../format/renderMarkdown.js";
import { buildMessages, type Mode } from "../skill/buildPrompt.js";
import { AUTO, LANGUAGES, outputLanguage, SOURCE } from "../skill/language.js";
import { listModels, resolveModel, streamCompletion, SipPulseError } from "../sippulse/client.js";
import {
  NoCaptionsError,
  NotPlayableError,
  TrackUnavailableError,
  type FetchedEpisode,
} from "../youtube/fetchEpisode.js";
import { seekTargetFrom } from "../youtube/seekTarget.js";
import { videoIdFrom } from "../youtube/videoId.js";
import { harvest, seek } from "./harvest.js";

declare const chrome: any;

const $ = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;

const evaluateButton = $<HTMLButtonElement>("evaluate");
const copyTranscriptButton = $<HTMLButtonElement>("copy-transcript");
const copySummaryButton = $<HTMLButtonElement>("copy-summary");
const status = $("status");
const details = $("details");
const summary = $("summary");
const languageSelect = $<HTMLSelectElement>("language");
const settings = $<HTMLDetailsElement>("settings");
const keyInput = $<HTMLInputElement>("key");
const saveKeyButton = $<HTMLButtonElement>("save-key");
const keyStatus = $("key-status");

/** The episode last harvested, so copying and evaluating the same video fetch it once. */
let harvested: { videoId: string; tabId: number; fetched: FetchedEpisode } | undefined;
let summaryMarkdown = "";
let running: AbortController | undefined;

function say(message: string, tone: "idle" | "busy" | "good" | "bad"): void {
  status.textContent = message;
  status.className = tone;
}

function sayFailure(error: unknown): void {
  if (
    error instanceof NoCaptionsError ||
    error instanceof NotPlayableError ||
    error instanceof TrackUnavailableError ||
    error instanceof SipPulseError
  ) {
    say(error.message, "bad");
  } else {
    say(`Something went wrong: ${String(error)}`, "bad");
  }
}

const countWords = (text: string): number => text.split(/\s+/).filter(Boolean).length;

function selectedMode(): Mode {
  return document.querySelector<HTMLInputElement>('input[name="mode"]:checked')?.value === "fast"
    ? "fast"
    : "complete";
}

/** Harvest whatever video the active tab is showing, or say why not. */
async function harvestActiveTab(): Promise<typeof harvested> {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const videoId = tab?.url ? videoIdFrom(tab.url) : undefined;

  if (!videoId) {
    say("Open a YouTube video first — this only works on a watch page.", "bad");
    return undefined;
  }

  if (harvested?.videoId !== videoId) {
    say("Fetching the transcript…", "busy");
    harvested = { videoId, tabId: tab.id, fetched: await harvest(tab.id, videoId) };
  }
  harvested.tabId = tab.id;

  const { warning, trackLanguage, trackIsAutoGenerated, episode } = harvested.fetched;
  details.textContent =
    warning ??
    `${trackLanguage}${trackIsAutoGenerated ? " · auto-generated" : " · human-written"}` +
      `${episode.chapters.length ? ` · ${episode.chapters.length} chapters` : ""}`;
  return harvested;
}

copyTranscriptButton.addEventListener("click", async () => {
  copyTranscriptButton.disabled = true;
  try {
    const current = await harvestActiveTab();
    if (!current) return;

    const transcript = formatForClipboard(current.fetched.episode);
    await navigator.clipboard.writeText(transcript);
    say(`Transcript copied — ${countWords(transcript).toLocaleString()} words.`, "good");
  } catch (error) {
    sayFailure(error);
  } finally {
    copyTranscriptButton.disabled = false;
  }
});

evaluateButton.addEventListener("click", async () => {
  if (running) {
    running.abort();
    return;
  }

  const { sippulseKey, sippulseModel } = await chrome.storage.local.get(["sippulseKey", "sippulseModel"]);
  if (!sippulseKey || !sippulseModel) {
    settings.open = true;
    keyInput.focus();
    say("Add your SipPulse AI key first.", "bad");
    return;
  }

  running = new AbortController();
  evaluateButton.textContent = "Stop";
  copySummaryButton.hidden = true;
  summary.replaceChildren();
  summaryMarkdown = "";
  details.textContent = "";

  try {
    const current = await harvestActiveTab();
    if (!current) return;

    const mode = selectedMode();
    const transcript = formatForClipboard(current.fetched.episode);
    const skill = await (await fetch(chrome.runtime.getURL("skill/SKILL.md"))).text();
    const language = outputLanguage(languageSelect.value, navigator.language);

    say(`Evaluating ${countWords(transcript).toLocaleString()} words…`, "busy");

    let frame = 0;
    const finishReason = await streamCompletion({
      apiKey: sippulseKey,
      model: sippulseModel,
      messages: buildMessages({ skill, transcript, mode, language }),
      signal: running.signal,
      onText: (text) => {
        summaryMarkdown += text;
        frame ||= requestAnimationFrame(() => {
          frame = 0;
          summary.innerHTML = renderMarkdown(summaryMarkdown);
        });
      },
    });

    cancelAnimationFrame(frame);
    summary.innerHTML = renderMarkdown(summaryMarkdown);

    if (!summaryMarkdown.trim()) {
      say("The model returned nothing. Try again.", "bad");
      return;
    }

    copySummaryButton.hidden = false;
    const trade = `${countWords(transcript).toLocaleString()} words → ${countWords(summaryMarkdown).toLocaleString()}`;
    if (finishReason === "length") {
      say(`The model ran out of room and the summary is cut off. ${trade}.`, "bad");
    } else {
      say(`Done — ${trade} · ${sippulseModel}`, "good");
    }
  } catch (error) {
    if (running.signal.aborted) {
      copySummaryButton.hidden = !summaryMarkdown.trim();
      say("Stopped.", "idle");
    } else {
      sayFailure(error);
    }
  } finally {
    running = undefined;
    evaluateButton.textContent = "Evaluate this video";
  }
});

copySummaryButton.addEventListener("click", async () => {
  await navigator.clipboard.writeText(summaryMarkdown);
  say("Summary copied as Markdown.", "good");
});

// A chapter anchor into the open video moves its player; any other link opens normally.
summary.addEventListener("click", (event) => {
  const link = (event.target as HTMLElement).closest("a");
  if (!link || !harvested) return;

  const seconds = seekTargetFrom(link.href, harvested.videoId);
  if (seconds === undefined) return;

  event.preventDefault();
  seek(harvested.tabId, seconds).catch(() => window.open(link.href, "_blank", "noopener"));
});

document.querySelectorAll<HTMLInputElement>('input[name="mode"]').forEach((radio) => {
  radio.addEventListener("change", () => chrome.storage.local.set({ mode: selectedMode() }));
});

languageSelect.append(
  new Option(`Browser language (${outputLanguage(AUTO, navigator.language)})`, AUTO),
  ...LANGUAGES.map((language) => new Option(language.label, language.value)),
  new Option("Same as the video", SOURCE),
);
languageSelect.addEventListener("change", () => chrome.storage.local.set({ language: languageSelect.value }));

saveKeyButton.addEventListener("click", async () => {
  const key = keyInput.value.trim();
  if (!key) {
    await chrome.storage.local.remove(["sippulseKey", "sippulseModel"]);
    keyStatus.textContent = "Key removed.";
    keyStatus.className = "idle";
    return;
  }

  saveKeyButton.disabled = true;
  keyStatus.textContent = "Checking the key…";
  keyStatus.className = "busy";

  try {
    // Listing the models proves the key works and finds the model in one request.
    const model = resolveModel(await listModels(key));
    await chrome.storage.local.set({ sippulseKey: key, sippulseModel: model });
    keyStatus.textContent = `Key saved. Using ${model}.`;
    keyStatus.className = "good";
    settings.open = false;
    say(`Key saved — using ${model}. Open a YouTube video and click Evaluate.`, "good");
  } catch (error) {
    keyStatus.textContent = error instanceof SipPulseError ? error.message : `Could not reach SipPulse AI: ${String(error)}`;
    keyStatus.className = "bad";
  } finally {
    saveKeyButton.disabled = false;
  }
});

const stored = await chrome.storage.local.get(["sippulseKey", "sippulseModel", "mode", "language"]);
if (stored.mode === "fast") $<HTMLInputElement>("mode-fast").checked = true;
// An unknown stored value leaves the select on its first option, which is auto.
if (stored.language) languageSelect.value = stored.language;
if (languageSelect.selectedIndex < 0) languageSelect.value = AUTO;
if (stored.sippulseKey) {
  keyInput.value = stored.sippulseKey;
  keyStatus.textContent = `Using ${stored.sippulseModel}.`;
} else {
  settings.open = true;
}
