import { NoCaptionsError, NotPlayableError, TrackUnavailableError } from "./errors.js";
import { parseTimedText } from "./parseTimedText.js";
import {
  captionTracksOf,
  describeEpisode,
  originalLanguageOf,
  playableDetails,
  type FetchedEpisode,
  type PlayerResponse,
} from "./playerResponse.js";
import { selectTrack, type TrackChoice } from "./selectTrack.js";

/**
 * Identify as the Android client.
 *
 * This is the whole reason this works. The WEB client's caption URLs carry an
 * `exp=xpe` parameter — a Proof-of-Origin gate we cannot satisfy — and serve an
 * empty body. The Android client's URLs carry no such parameter and serve the
 * track normally. Same endpoint, same video; only the claimed client differs.
 */
const ANDROID_CLIENT = {
  clientName: "ANDROID",
  clientVersion: "20.10.38",
  androidSdkVersion: 30,
  hl: "en",
  gl: "US",
} as const;

const PLAYER_URL = "https://www.youtube.com/youtubei/v1/player";

/** How a caller reaches YouTube: directly from Node, or from inside the page in the extension. */
export type Fetcher = (
  url: string,
  init: RequestInit,
) => Promise<{ ok: boolean; status: number; body: string }>;

/** The body to POST to the player endpoint. Shared so every caller claims the same client. */
export function playerRequest(videoId: string): { url: string; init: RequestInit } {
  return {
    url: PLAYER_URL,
    init: {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Youtube-Client-Name": "3",
        "X-Youtube-Client-Version": ANDROID_CLIENT.clientVersion,
      },
      body: JSON.stringify({ context: { client: ANDROID_CLIENT }, videoId }),
    },
  };
}

/**
 * Choose the caption track from a player response. Pure — separated from the
 * network so the extension can do its fetching inside the page (same-origin)
 * while sharing this logic.
 */
export function pickTrack(payload: PlayerResponse, videoId: string): TrackChoice {
  playableDetails(payload);
  const choice = selectTrack(captionTracksOf(payload), originalLanguageOf(payload));
  if (!choice) throw new NoCaptionsError(videoId);
  return choice;
}

/**
 * Check that a caption-track response really is a caption track. Pure.
 *
 * A blocked timedtext request is not answered with an error the way the player
 * endpoint answers one — YouTube serves an HTTP 429 carrying Google's "Sorry"
 * interstitial. That page parses to zero cues, and zero cues used to surface as
 * "this episode has no captions", which blames the episode for a block on the
 * network. The track list said the captions exist; believe it.
 */
export function assertTrackBody(status: number, body: string): void {
  if (status === 429 || /automated queries/i.test(body)) {
    throw new TrackUnavailableError(
      "YouTube is refusing caption downloads from this network right now " +
        `(HTTP ${status}). The episode does have captions — YouTube's own player ` +
        "cannot load them here either. Try again later or from another network.",
    );
  }

  if (status >= 400) {
    throw new TrackUnavailableError(`YouTube refused to serve the caption track (HTTP ${status}).`);
  }

  if (!/<(?:p|text)[\s>]/.test(body)) {
    throw new TrackUnavailableError(
      "YouTube returned something that is not a caption track. " +
        "The episode has captions, but they could not be downloaded.",
    );
  }
}

/** Assemble the episode from a player response and its fetched track. Pure. */
export function buildEpisode(
  payload: PlayerResponse,
  xml: string,
  videoId: string,
  choice: TrackChoice,
): FetchedEpisode {
  const cues = parseTimedText(xml);
  if (cues.length === 0) throw new NoCaptionsError(videoId);

  const episode = { ...describeEpisode(payload, videoId), segments: cues.map((cue) => ({ text: cue.text })) };

  return {
    episode,
    ...(choice.warning ? { warning: choice.warning } : {}),
    trackLanguage: choice.track.languageCode,
    trackIsAutoGenerated: choice.track.kind === "asr",
  };
}

/**
 * Harvest one episode through whatever fetcher the caller has.
 *
 * The sequence — player request, track choice, track download, body check —
 * lives here once. The CLI and the extension differ only in where the request
 * is allowed to come from, which is the fetcher's business.
 */
export async function fetchEpisodeWith(fetcher: Fetcher, videoId: string): Promise<FetchedEpisode> {
  const { url, init } = playerRequest(videoId);
  const player = await fetcher(url, init);
  if (!player.ok) throw new NotPlayableError(`YouTube refused the request (HTTP ${player.status}).`);

  const payload = JSON.parse(player.body) as PlayerResponse;
  const choice = pickTrack(payload, videoId);

  const track = await fetcher(choice.track.baseUrl, {});
  assertTrackBody(track.status, track.body);
  return buildEpisode(payload, track.body, videoId, choice);
}

/** Fetch an episode directly. Used by the CLI, where no browser origin is involved. */
export function fetchEpisode(videoId: string): Promise<FetchedEpisode> {
  return fetchEpisodeWith(async (url, init) => {
    const response = await fetch(url, init);
    return { ok: response.ok, status: response.status, body: await response.text() };
  }, videoId);
}
