import { formatForClipboard } from "../format/formatForClipboard.js";
import { renderMarkdown } from "../format/renderMarkdown.js";
import { buildMessages } from "../skill/buildPrompt.js";
import { AUTO, LANGUAGES, languageChoiceFrom, outputLanguage, SOURCE } from "../skill/language.js";
import { listModels, ModelUnavailableError, resolveModel, streamCompletion, SipPulseError, } from "../sippulse/client.js";
import { EpisodeError } from "../youtube/errors.js";
import { seekTargetFrom } from "../youtube/seekTarget.js";
import { activeVideo, harvest, isStillWatching, seek } from "./harvest.js";
import { setUpKeyForm } from "./keyForm.js";
import { say } from "./say.js";
import { loadSettings, saveLanguage, saveMode } from "./settings.js";
const $ = (id) => document.getElementById(id);
const evaluateButton = $("evaluate");
const copyTranscriptButton = $("copy-transcript");
const copySummaryButton = $("copy-summary");
const details = $("details");
const summary = $("summary");
const languageSelect = $("language");
/** The episode last harvested, so copying and evaluating the same video fetch it once. */
let harvested;
/** The video the summary on screen is about — not necessarily the one last harvested. */
let evaluated;
let summaryMarkdown = "";
let running;
const report = (message, tone) => say($("status"), message, tone);
function reportFailure(error) {
    if (error instanceof ModelUnavailableError)
        console.info("Models this key can use:", error.seen);
    if (error instanceof EpisodeError || error instanceof SipPulseError) {
        report(error.message, "bad");
    }
    else {
        report(`Something went wrong: ${String(error)}`, "bad");
    }
}
const countWords = (text) => text.split(/\s+/).filter(Boolean).length;
function selectedMode() {
    return document.querySelector('input[name="mode"]:checked')?.value === "fast"
        ? "fast"
        : "complete";
}
/** What was harvested, in a line: the track's language, who wrote it, how many chapters. */
function describeTrack({ warning, trackLanguage, trackIsAutoGenerated, episode }) {
    if (warning)
        return warning;
    const track = trackLanguage ? `${trackLanguage} · ${trackIsAutoGenerated ? "auto-generated" : "human-written"}` : "";
    const chapters = episode.chapters.length ? `${episode.chapters.length} chapters` : "";
    return [track, chapters].filter(Boolean).join(" · ");
}
async function harvestOnce(video) {
    if (harvested?.videoId !== video.videoId) {
        report("Fetching the transcript…", "busy");
        harvested = { videoId: video.videoId, fetched: await harvest(video.tabId, video.videoId) };
    }
    details.textContent = describeTrack(harvested.fetched);
    return harvested.fetched;
}
/** The video to act on, or undefined after telling the user there is none. */
async function videoOrExplain() {
    const video = await activeVideo();
    if (!video)
        report("Open a YouTube video first — this only works on a watch page.", "bad");
    return video;
}
/**
 * Resolve the model on every evaluation rather than storing its id: a catalog
 * that renamed or dropped it would otherwise fail every evaluation with an
 * error that never says "save your key again".
 */
const currentModel = async (apiKey) => resolveModel(await listModels(apiKey));
// Loaded before any button is wired, so no click can arrive ahead of the settings.
const stored = await loadSettings();
const keyForm = setUpKeyForm(stored, () => report("Key saved. Open a YouTube video and click Evaluate.", "good"));
copyTranscriptButton.addEventListener("click", async () => {
    copyTranscriptButton.disabled = true;
    try {
        const video = await videoOrExplain();
        if (!video)
            return;
        const transcript = formatForClipboard((await harvestOnce(video)).episode);
        await navigator.clipboard.writeText(transcript);
        report(`Transcript copied — ${countWords(transcript).toLocaleString()} words.`, "good");
    }
    catch (error) {
        reportFailure(error);
    }
    finally {
        copyTranscriptButton.disabled = false;
    }
});
evaluateButton.addEventListener("click", async () => {
    if (running) {
        running.abort();
        return;
    }
    const settings = await loadSettings();
    if (!settings.apiKey) {
        keyForm.askForKey();
        report("Add your SipPulse AI key first.", "bad");
        return;
    }
    const stop = (running = new AbortController());
    let frame = 0;
    evaluateButton.textContent = "Stop";
    copySummaryButton.hidden = true;
    summary.replaceChildren();
    summaryMarkdown = "";
    evaluated = undefined;
    details.textContent = "";
    try {
        const video = await videoOrExplain();
        if (!video)
            return;
        const [fetched, model] = await Promise.all([harvestOnce(video), currentModel(settings.apiKey)]);
        const transcript = formatForClipboard(fetched.episode);
        const skill = await (await fetch(chrome.runtime.getURL("skill/SKILL.md"))).text();
        evaluated = video;
        report(`Evaluating ${countWords(transcript).toLocaleString()} words…`, "busy");
        const finishReason = await streamCompletion({
            apiKey: settings.apiKey,
            model,
            messages: buildMessages({
                skill,
                transcript,
                mode: selectedMode(),
                language: outputLanguage(languageChoiceFrom(languageSelect.value), navigator.language),
            }),
            signal: stop.signal,
            onText: (text) => {
                summaryMarkdown += text;
                frame ||= requestAnimationFrame(() => {
                    frame = 0;
                    summary.innerHTML = renderMarkdown(summaryMarkdown);
                });
            },
        });
        const trade = `${countWords(transcript).toLocaleString()} words → ${countWords(summaryMarkdown).toLocaleString()}`;
        if (!summaryMarkdown.trim()) {
            report("The model returned nothing. Try again.", "bad");
        }
        else if (finishReason === "length") {
            report(`The model ran out of room and the summary is cut off. ${trade}.`, "bad");
        }
        else {
            report(`Done — ${trade}.`, "good");
        }
    }
    catch (error) {
        if (stop.signal.aborted)
            report("Stopped.", "idle");
        else
            reportFailure(error);
    }
    finally {
        // However it ended — done, stopped, or failed mid-stream — what arrived is on
        // screen, so it is rendered in full and can be copied.
        cancelAnimationFrame(frame);
        summary.innerHTML = renderMarkdown(summaryMarkdown);
        copySummaryButton.hidden = !summaryMarkdown.trim();
        running = undefined;
        evaluateButton.textContent = "Evaluate this video";
    }
});
copySummaryButton.addEventListener("click", async () => {
    await navigator.clipboard.writeText(summaryMarkdown);
    report("Summary copied as Markdown.", "good");
});
// A chapter anchor moves the open player — but only while the user is still watching
// the video the summary is about. Otherwise it opens like any link, which is also
// right: a new tab on that video, at that second.
summary.addEventListener("click", (event) => {
    const link = event.target.closest("a");
    const video = evaluated;
    if (!link || !video)
        return;
    const seconds = seekTargetFrom(link.href, video.videoId);
    if (seconds === undefined)
        return;
    event.preventDefault();
    isStillWatching(video)
        .then((watching) => (watching ? seek(video.tabId, seconds) : Promise.reject()))
        .catch(() => window.open(link.href, "_blank", "noopener"));
});
document.querySelectorAll('input[name="mode"]').forEach((radio) => {
    radio.checked = radio.value === stored.mode;
    radio.addEventListener("change", () => saveMode(selectedMode()));
});
languageSelect.append(new Option(`Browser language (${outputLanguage(AUTO, navigator.language)})`, AUTO), ...LANGUAGES.map((language) => new Option(language.label, language.value)), new Option("Same as the video", SOURCE));
languageSelect.value = stored.language;
languageSelect.addEventListener("change", () => saveLanguage(languageChoiceFrom(languageSelect.value)));
